airbnb:
  outputs:
    dev:
      type: snowflake
      account: mmojzbp-tx79176
      user: dbt
      role: TRANSFORM
      private_key_path: '{{ env_var(''SNOWFLAKE_PRIVATE_KEY_PATH'') }}'
      private_key_passphrase: q
      database: AIRBNB
      schema: DEV
      threads: 1
      warehouse: COMPUTE_WH
    qua:
      account: mmojzbp-tx7917
      database: AIRBNB_QUA
      private_key_path: '{{ env_var(''SNOWFLAKE_PRIVATE_KEY_PATH'') }}'
      private_key_passphrase: q
      role: TRANSFORM
      schema: QUAL
      threads: 1
      type: snowflake
      user: dbt_qual
      warehouse: COMPUTE_WH
  target: dev
