
name: dbt CD

on:
  push:
    branches:
      - main
      - develop
      - preprod

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DBT_PROFILES_DIR: ./airbnb

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Snowflake private key
        run: |
          mkdir -p /home/runner/.secrets
          echo "${{ secrets.SNOWFLAKE_PRIVATE_KEY_B64 }}" | base64 --decode > /home/runner/.secrets/snowflake_key.p8
          chmod 600 /home/runner/.secrets/snowflake_key.p8
        env:
          SNOWFLAKE_PRIVATE_KEY_PATH: /home/runner/.secrets/snowflake_key.p8

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dbt-snowflake
        run: pip install dbt-snowflake==1.11.4

      - name: Create profiles.yml
        run: |
          cat <<EOF > ./airbnb/profiles.yml
            airbnb:
              target: ${{ github.ref_name }}
              outputs:
                main:
                  type: snowflake
                  account: "${{ secrets.SNOWFLAKE_ACCOUNT }}"
                  user: "${{ secrets.SNOWFLAKE_USER }}"
                  private_key_path: "{{ env_var('SNOWFLAKE_PRIVATE_KEY_PATH') }}"
                  role: "${{ secrets.SNOWFLAKE_ROLE }}"
                  warehouse: "${{ secrets.SNOWFLAKE_WAREHOUSE }}"
                  database: "${{ secrets.SNOWFLAKE_DATABASE_PROD }}"
                  schema: airbnb_prod
                develop:
                  type: snowflake
                  account: "${{ secrets.SNOWFLAKE_ACCOUNT }}"
                  user: "${{ secrets.SNOWFLAKE_USER }}"
                  private_key_path: "{{ env_var('SNOWFLAKE_PRIVATE_KEY_PATH') }}"
                  role: "${{ secrets.SNOWFLAKE_ROLE }}"
                  warehouse: "${{ secrets.SNOWFLAKE_WAREHOUSE }}"
                  database: "${{ secrets.SNOWFLAKE_DATABASE_DEV }}"
                  schema: airbnb_dev
                preprod:
                  type: snowflake
                  account: "${{ secrets.SNOWFLAKE_ACCOUNT }}"
                  user: "${{ secrets.SNOWFLAKE_USER }}"
                  private_key_path: "{{ env_var('SNOWFLAKE_PRIVATE_KEY_PATH') }}"
                  role: "${{ secrets.SNOWFLAKE_ROLE }}"
                  warehouse: "${{ secrets.SNOWFLAKE_WAREHOUSE }}"
                  database: "${{ secrets.SNOWFLAKE_DATABASE_PREPROD }}"
                  schema: airbnb_preprod
          EOF

      - name: Install dependencies
        env:
          SNOWFLAKE_PRIVATE_KEY_PATH: /home/runner/.secrets/snowflake_key.p8
        run: dbt deps --project-dir ./airbnb --profiles-dir ./airbnb --target ${{ github.ref_name }}

      - name: Run dbt build
        env:
          SNOWFLAKE_PRIVATE_KEY_PATH: /home/runner/.secrets/snowflake_key.p8
        run: dbt build --project-dir ./airbnb --profiles-dir ./airbnb --target ${{ github.ref_name }}

      - name: Generate dbt docs
        env:
          SNOWFLAKE_PRIVATE_KEY_PATH: /home/runner/.secrets/snowflake_key.p8
        run: dbt docs-generate --project-dir ./airbnb --profiles-dir ./airbnb --target ${{ github.ref_name }}

      - name: Upload dbt artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dbt-manifest-${{ github.ref_name }}
          path: |
            ./airbnb/target/manifest.json
            ./airbnb/target/run_results.json
            ./airbnb/target/sources.json
